#!/bin/bash
#######################################################
#Atuor:qingbo.song
#Date:2016.11.02
#Comment:初始化脚本
#E-mail:qingbo.song@gmail.com
#github:https://github.com/swht/RaspberryPiMTV.git
#Version:v1.0
#######################################################